Game integration
akolgano/ft_transcendence pull request #14
Opened 2024-09-28 00:44 UTC by nickchua3998

Have added PvP, PvAI and also tournament signup .... unable to start tournament play yet, WIP and proving more challenging than I expect it to be ...

2024-09-29 15:15 UTC, barbayjuliette requested changes
Game looks good and is working but several things need to be fixed.

2024-09-29 15:15 UTC, barbayjuliette commented on frontend/js/pong_game.js
Instead of putting all the js and html in the same page and then changing the display, you could do it in several pages. One for registration, one for the game. So that you only load the JS for the game once you start playing

2024-09-29 15:15 UTC, barbayjuliette commented on frontend/js/pong_game.js
Sometimes the ball is super fast, sometimes at a normal speed when I start the game.
See the difference between both videos

https://github.com/user-attachments/assets/e5f7201a-e504-4f16-aba4-b0ab351054ce

https://github.com/user-attachments/assets/e4f47f7d-c31b-4a58-b47c-1e89810a00ad

2024-09-30 08:20 UTC, barbayjuliette commented
The back button from the browser doesn't work properly. 
If I am in the tournament -> Enter Player Names, and click on the back button from the browser, It will lead me for example to /friends. Or if I start the game, and then go back, it should still lead me to "Please select a Game ..."
This is because all the pages are actually one page. --> Make it into different pages.
This could be just 2 pages:
- game (= choose game type)
  and insert to the DOM the choice of usernames for players.
- play

2024-09-30 08:24 UTC, barbayjuliette commented
STYLING:
- Keep the background in white to have consistent styling (for the game and game selection). But game in black (with border)

![pong](https://github.com/user-attachments/assets/d02143d5-99e4-4658-943f-755d689b8882)
Add the score and names on top. Something similar to the picture.

2024-10-04 06:00 UTC, barbayjuliette commented
Error in the console to fix: 
Uncaught SyntaxError: Identifier 'ball' has already been declared
    at urlRouter.js:178:17
    at Array.forEach (<anonymous>)
    at addScripts (urlRouter.js:174:10)
    at loadScripts (urlRouter.js:188:2)
    at urlLocationHandler (urlRouter.js:165:2)
    at urlRoute (urlRouter.js:123:2)
    at HTMLAnchorElement.spaHandler (urlRouter.js:110:2)
    
 --> Everything is in the global scope so when the script is called again, the values have already been defined. What I did for some of my script is put everything between curly braces, so the variables get destroyed after, and do not stay in global scope

2024-10-04 06:03 UTC, barbayjuliette commented
If I play, and I leave (go to another page from the site) the game, it continues playing in the background.
But then I click on play again, and I cannot see any game in progress, I have to choose the type of game, and when the game start, there is no countdown
=> The game should stop or pause when I change to another page from the site.

2024-10-04 06:03 UTC, barbayjuliette commented
Error in console: 
Uncaught TypeError: Cannot read properties of null (reading 'style')
    at showGameOverModalPP (<anonymous>:442:17)
    at gameLoop (<anonymous>:472:4)

2024-10-12 07:40 UTC, closed without merging

2024-10-12 15:53 UTC, nickchua3998 commented on frontend/js/pong_game.js
gone through ... looks ok.  be precise which lines are not properly indented.  General comments like this is not useful.

2024-10-12 15:54 UTC, nickchua3998 commented on frontend/css/styles.css
> +body {
done

2024-10-12 15:54 UTC, nickchua3998 commented on frontend/css/styles.css
> +button {
dont understand bootstrap ... will have to come back after I figure out bootstrap

2024-10-12 15:55 UTC, nickchua3998 commented on frontend/play.html
> +        <button onclick="startPlayerVsPlayer()">Player vs Player</button>
BS issue ... has to wait

2024-10-12 15:56 UTC, nickchua3998 commented on frontend/game.html
> +		<h1>Game Over!</h1>
I think I need to deal with BS issue then can come back to deal with the translation ... the syntax is embedded into that of BS ... so need to figure out BS

2024-10-12 15:58 UTC, nickchua3998 commented on frontend/play.html
> +    <script src="js/game.js"></script>
done ... ok, I will deal with this in the next iterations

2024-10-12 15:58 UTC, nickchua3998 commented on frontend/game.html
deleted

2024-10-12 15:58 UTC, nickchua3998 commented on frontend/game.html
> +    <script src="{% static 'js/game.js' %}"></script> <!-- Link to game.js script -->
deleted

2024-10-12 16:00 UTC, nickchua3998 commented on frontend/js/pong_game.js
can consider ... give me your preferred approach and then I can think about implementing it.  I currently see it as something that needs to continue to run as a game / tournament sequence.  Not so easy to break it into several pages.

2024-10-12 16:02 UTC, nickchua3998 commented on frontend/js/pong_game.js
tackled it by resetting the game parameters if we are jumping around.  If you pick it up again, need to be more precise with the circumstances of how it happens.  what happens before this video sequence should inform.

2024-10-12 16:04 UTC, nickchua3998 commented
> STYLING:
> 
> * Keep the background in white to have consistent styling (for the game and game selection). But game in black (with border)
> 
> ![pong](https://private-user-images.githubusercontent.com/109951226/372003947-d02143d5-99e4-4658-943f-755d689b8882.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NDg1ODUsIm5iZiI6MTcyODc0ODI4NSwicGF0aCI6Ii8xMDk5NTEyMjYvMzcyMDAzOTQ3LWQwMjE0M2Q1LTk5ZTQtNDY1OC05NDNmLTc1NWQ2ODliODg4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQxNTUxMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2ViODc3MDc5ZTNmYTdmOTA5MTQ5YzIxMmM5ZjM0ZGY2YTlkMjM5NTAzNDVhZDE2ZjFmZWE4NjczOTYyOWUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.geYfEeBGiXrTy7BwrYo7vj_mzdFEnlBV1CW-wIUC_I0) Add the score and names on top. Something similar to the picture.
> 
> * change style to Bootstrap

We need not follow others ... I quite like my design ...

2024-10-12 16:05 UTC, nickchua3998 commented
> If I play, and I leave (go to another page from the site) the game, it continues playing in the background. But then I click on play again, and I cannot see any game in progress, I have to choose the type of game, and when the game start, there is no countdown => The game should stop or pause when I change to another page from the site.

Tackled ....

2024-10-13 07:48 UTC, barbayjuliette commented on frontend/js/pong_game.js
Maybe it changed in the new version. But in this branch, from line2 onwards it is wrongly indented

2024-10-13 07:57 UTC, barbayjuliette commented on frontend/js/pong_game.js
Page to chose type of game: tournament or 1v1 game.
I choose and it redirects me to the registration page for either tournament or 1v1 game. 
Then I start, and I have another page for the game itself.

Pages: game choice / 1v1 game registration / tournament registration / game (+ tournament board?).
User cannot access game if they haven't registered to play.
Verify that the name of the opponent(s) is not the same as the user (check how to get the name of the user by by doing a global search of localstorage).

2024-10-13 12:11 UTC, barbayjuliette commented
VM68:1 Uncaught SyntaxError: Identifier 'ball' has already been declared
    at urlRouter.js:219:17
    at Array.forEach (<anonymous>)
    at addScripts (urlRouter.js:215:10)
    at loadScripts (urlRouter.js:229:2)
    at urlLocationHandler (urlRouter.js:206:2)
VM70:1 Uncaught SyntaxError: Identifier 'matchIndex' has already been declared
    at urlRouter.js:219:17
    at Array.forEach (<anonymous>)
    at addScripts (urlRouter.js:215:10)
    at loadScripts (urlRouter.js:229:2)
    at urlLocationHandler (urlRouter.js:206:2)
    
    
    Those errors come from your JS files