Fix language labels
akolgano/ft_transcendence pull request #97
Opened 2024-10-31 09:39 UTC by chinwenkai

Having difficulties implementing translation for the chart pop up labels. Amended to show numbers/values only.
Increased screen width coverage for graphs.
![image](https://github.com/user-attachments/assets/e020f316-144e-4093-8bdf-064aa47fc5a1)

2024-11-01 08:55 UTC, barbayjuliette commented
Hover on the pie graphs is not accurate. 
I hover the blue, it the hover is for the red.

Game Margin Distribution of all games:
Add a description of what it shows. Because it is not so clear what it is trying to show.

Size of the graphs on the VM? Did you fix it and test it in the VM? 
I cannot test it now

2024-11-01 08:56 UTC, barbayjuliette requested changes
See comments

2024-11-01 08:56 UTC, barbayjuliette commented on pong/media/profile_pictures/redpanda.jpg
You removed this picture. You need to put it back!

2024-11-01 15:17 UTC, barbayjuliette commented
Remove all your console.log

2024-11-02 11:28 UTC, chinwenkai commented
The charts are larger on the VM after changing from
<div class="col-12 col-md-6"> to <div class="col-12 col-md-8">
![image](https://github.com/user-attachments/assets/8d8f1f2d-a715-4301-8da8-364fa3da2eb8)

This seems to cause pop up misalignment on laptop, but no alignment issues on 42 VM.

2024-11-02 13:18 UTC, chinwenkai commented
Hover accuracy fixed

Game Margin Distribution description amended.

size tested on VM

2024-11-02 13:27 UTC, chinwenkai commented
console.log removed

2024-11-03 09:12 UTC, barbayjuliette commented
> Issue encountered on 42 VM?

In 42 VM for yellow part of pie, in Firefox

2024-11-03 09:23 UTC, barbayjuliette commented
Okay, now looks okay in VM

2024-11-03 09:24 UTC, barbayjuliette commented
Just need to change the style to Bootstrap, then we can merge

2024-11-03 09:25 UTC, barbayjuliette commented
@chinwenkai 
The pie graphs do not have the same size in Firefox and Chrome.
Too big in Firefox. Make it same size in both.

2024-11-03 09:27 UTC, barbayjuliette commented
The hover also doesn't work properly in Firefox. 
Especially on the Game margin graph, yellow color

2024-11-03 09:44 UTC, chinwenkai commented
https://github.com/user-attachments/assets/708be724-1add-4124-90bd-e3b4ce4c92eb

Firefox pop up seems ok for my side

2024-11-03 09:46 UTC, chinwenkai commented
Issue encountered on 42 VM?

2024-11-03 14:42 UTC, chinwenkai commented
styles changed to bootstrap class in dashboard.html

2024-11-03 14:52 UTC, barbayjuliette commented
@chinwenkai remove from styles

2024-11-03 14:56 UTC, chinwenkai commented
Removed from chart widths from styles.css

2024-11-03 14:58 UTC, barbayjuliette commented
<img width="304" alt="Screenshot 2024-11-03 at 22 58 00" src="https://github.com/user-attachments/assets/c5533c49-60b5-451a-b8e8-5d01447a6908">
<img width="270" alt="Screenshot 2024-11-03 at 22 56 25" src="https://github.com/user-attachments/assets/bd7b1b8a-b6a1-4cf8-8362-a0f72085ebdc">
Labels missing

2024-11-03 15:10 UTC, barbayjuliette commented
<hr class="flex-shrink-0 border-0" style="border: 10px solid rgba(54, 162, 235, 0.6); width: 2%; margin: 0; opacity: 1;">

- You have border twice
- It is not good to use inline styles, some can be replaced with bootstrap (border: 10px solid margin opacity)

2024-11-03 15:40 UTC, barbayjuliette commented
To do this in Bootstrap:

   width: 100%;
    height: auto;
    
    You just need to add 2 classes, you do not need to redo everything!
    Jut a google search with bootstrap will give you the answer...

2024-11-04 02:41 UTC, barbayjuliette approved these changes
ok

2024-11-04 02:41 UTC, merged